# Generated by Django 5.1.2 on 2025-11-10 20:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloblog',
            name='imagen_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_portada'),
        ),
        migrations.AlterField(
            model_name='fotorestaurante',
            name='url_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_restaurante'),
        ),
        migrations.AlterField(
            model_name='fotoslugares',
            name='url_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_lugar'),
        ),
        migrations.AlterField(
            model_name='fotosresena',
            name='url_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_resena'),
        ),
        migrations.AlterField(
            model_name='galeriacomunitaria',
            name='url_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_galeria'),
        ),
        migrations.AlterField(
            model_name='lugaresturisticos',
            name='imagen_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_lugar'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_platillo'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
