# Generated by Django 5.1.2 on 2025-11-28 14:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_resena_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plataforma', models.CharField(default='El Sabor de la Perla del Pacífico', max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo_plataforma')),
                ('correo_contacto', models.EmailField(default='contacto@elsabor.com', max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_general', models.CharField(blank=True, max_length=255, null=True)),
                ('horarios_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
                ('url_facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('url_instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('url_twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('url_tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('url_youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('url_whatsapp', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Plataforma',
                'verbose_name_plural': 'Configuración de la Plataforma',
            },
        ),
    ]
