# Generated by Django 5.1.2 on 2025-12-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_configuracionplataforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articuloblog',
            name='autor',
        ),
    ]
