# Generated by Django 5.1.2 on 2025-12-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_articuloblog_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('abre', models.TimeField(blank=True, null=True)),
                ('cierra', models.TimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.restaurante')),
            ],
            options={
                'unique_together': {('restaurante', 'dia')},
            },
        ),
    ]
