# Generated by Django 5.1.2 on 2025-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_horariorestaurante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariorestaurante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horariorestaurante',
            name='horario',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='horariorestaurante',
            name='abre',
        ),
        migrations.RemoveField(
            model_name='horariorestaurante',
            name='cerrado',
        ),
        migrations.RemoveField(
            model_name='horariorestaurante',
            name='cierra',
        ),
        migrations.RemoveField(
            model_name='horariorestaurante',
            name='dia',
        ),
    ]
