# Generated by Django 6.0 on 2025-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajescontacto',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
