# Generated by Django 6.0 on 2025-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mensajescontacto_archivado_testimonio_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajescontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
