# Generated by Django 5.1.2 on 2025-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mensajescontacto_leido'),
    ]

    operations = [
    ]
