# Generated by Django 5.1.2 on 2025-12-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_restaurante_sitio_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajescontacto',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
