# Generated by Django 5.1.2 on 2025-12-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_restaurante_url_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_facebook',
        ),
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_instagram',
        ),
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_tiktok',
        ),
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_twitter',
        ),
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_whatsapp',
        ),
        migrations.RemoveField(
            model_name='configuracionplataforma',
            name='url_youtube',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='sitio_web',
        ),
    ]
