# Generated by Django 5.1.2 on 2025-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_configuracionplataforma_url_facebook_and_more'),
    ]

    operations = [
    ]
