# Generated by Django 5.1.2 on 2025-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_restaurante_url_facebook_restaurante_url_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_tiktok',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_whatsapp',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionplataforma',
            name='url_youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        )
    ]
