# Generated by Django 5.1.2 on 2025-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_configuracionplataforma_url_facebook_and_more'),
    ]

    operations = [
    ]
