# Generated by Django 5.1.2 on 2025-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_restaurante_url_facebook_restaurante_url_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paypal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('sinpe', 'SINPE Móvil'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
