# Generated by Django 5.1.2 on 2025-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pedido_paypal_order_id_pedido_paypal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='paypal_status',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('sinpe', 'SINPE Móvil'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
